"""Block 1 of the study pre-registered in HYPOTHESES.md: forecast accuracy.

Usage (from the repo root):
    .venv/bin/python research/block1_forecasts.py              # full run
    .venv/bin/python research/block1_forecasts.py --download   # re-download data first
    .venv/bin/python research/block1_forecasts.py --report-only  # figures + RESULTS.md from saved tables

Stages:
    1. data      ^GSPC daily OHLC from Yahoo into data/, manifest into results/
    2. forecast  walk-forward forecasts at every out-of-sample origin t
    3. evaluate  QLIKE / MSE, Diebold-Mariano, Mincer-Zarnowitz, by period
    4. report    figures and RESULTS.md, read back from the saved tables
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import sys
from pathlib import Path
from zoneinfo import ZoneInfo

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from find_edge import models  # noqa: E402
from find_edge.signals import TRADING_DAYS_PER_YEAR  # noqa: E402

DATA_FILE = ROOT / "data" / "gspc_daily.csv"
RESULTS = ROOT / "results"
FIGURES = RESULTS / "figures"
MANIFEST = RESULTS / "data_manifest.json"
FORECASTS_CSV = RESULTS / "block1_forecasts.csv"
LOSSES_CSV = RESULTS / "block1_losses.csv"
DM_CSV = RESULTS / "block1_dm.csv"
MZ_CSV = RESULTS / "block1_mz.csv"
RESULTS_MD = RESULTS / "RESULTS.md"
# research/block2_vrp.py owns everything from this line on; Block 1 keeps it.
BLOCK2_MARKER = "<!-- BLOCK 2: generated by research/block2_vrp.py -->"

# Pre-specified in HYPOTHESES.md.
TICKER = "^GSPC"
START = "2000-01-01"
OOS_START = "2005-01-01"
HORIZON = 21
NW_LAGS = 20
ALPHA = 0.05
N_VS_NAIVE = 3
MODELS = ("naive", "ewma", "garch", "har")
FULL = "2005-latest"
PERIODS = {
    FULL: ("2005-01-01", None),
    "2005-2012": ("2005-01-01", "2012-12-31"),
    "2013-2019": ("2013-01-01", "2019-12-31"),
    "2020-latest": ("2020-01-01", None),
}
VS_NAIVE = [(m, "naive") for m in ("ewma", "garch", "har")]
VS_EWMA = [("garch", "ewma"), ("har", "ewma")]


# --- 1. data ----------------------------------------------------------------


def download_data() -> None:
    """Fetch ^GSPC daily OHLC from START to the latest completed close."""
    import yfinance as yf

    hist = yf.Ticker(TICKER).history(start=START, interval="1d", auto_adjust=False)
    if hist.empty:
        raise RuntimeError(f"Yahoo returned no rows for {TICKER}")
    df = hist[["Open", "High", "Low", "Close", "Volume"]].copy()
    df.index = pd.to_datetime(df.index.date)
    df.index.name = "Date"

    # Drop today's bar if the New York session has not closed yet.
    ny = dt.datetime.now(ZoneInfo("America/New_York"))
    if df.index[-1].date() == ny.date() and ny.time() < dt.time(17, 0):
        df = df.iloc[:-1]

    DATA_FILE.parent.mkdir(exist_ok=True)
    df.to_csv(DATA_FILE)
    RESULTS.mkdir(exist_ok=True)
    # Keep entries other blocks added (e.g. "vix"); the S&P fields stay top-level.
    manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    manifest.update(
        {
            "source": f"Yahoo Finance via yfinance {yf.__version__}",
            "ticker": TICKER,
            "fields": list(df.columns),
            "interval": "1d",
            "file": str(DATA_FILE.relative_to(ROOT)),
            "download_date": dt.date.today().isoformat(),
            "first_date": df.index[0].date().isoformat(),
            "last_date": df.index[-1].date().isoformat(),
            "rows": len(df),
            "sha256": hashlib.sha256(DATA_FILE.read_bytes()).hexdigest(),
        }
    )
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")


def load_log_returns() -> pd.Series:
    close = pd.read_csv(DATA_FILE, index_col="Date", parse_dates=True)["Close"]
    return np.log(close).diff().dropna().rename("r")


# --- 2. forecast ------------------------------------------------------------


def realised_vol_target(r: pd.Series, horizon: int = HORIZON) -> pd.Series:
    """RV(t+1, t+horizon) = sqrt(252 * mean squared log return), indexed by t."""
    mean_r2 = r.pow(2).rolling(horizon).mean().shift(-horizon)
    return np.sqrt(TRADING_DAYS_PER_YEAR * mean_r2).rename("rv")


def make_forecasts(
    r: pd.Series, origins: pd.DatetimeIndex, horizon: int = HORIZON
) -> pd.DataFrame:
    """Walk-forward forecasts. At each origin t every model sees r up to t only.

    GARCH and HAR are refitted on the first origin of each calendar month,
    on data up to that origin, and held fixed until the next refit.
    """
    rows, month, gp, hc = [], None, None, None
    for t in origins:
        past = r.loc[:t]
        if t.to_period("M") != month:
            month = t.to_period("M")
            gp = models.garch_fit(past)
            hc = models.har_fit(past, horizon)
        rows.append(
            {
                "date": t,
                "naive": models.naive(past, horizon),
                "ewma": models.ewma(past, horizon),
                "garch": models.garch(past, horizon, params=gp),
                "har": models.har(past, horizon, coefs=hc),
            }
        )
    return pd.DataFrame(rows).set_index("date")


def run_forecasts() -> None:
    r = load_log_returns()
    rv = realised_vol_target(r)
    origins = rv.loc[OOS_START:].dropna().index
    fc = make_forecasts(r, origins)
    fc.insert(0, "rv", rv.loc[origins])
    fc.to_csv(FORECASTS_CSV, float_format="%.8f")


# --- 3. evaluate ------------------------------------------------------------


def qlike(rv: pd.Series, f: pd.Series) -> pd.Series:
    """QLIKE on variance, normalised to 0 for a perfect forecast."""
    ratio = rv**2 / f**2
    return ratio - np.log(ratio) - 1


def mse(rv: pd.Series, f: pd.Series) -> pd.Series:
    return (rv**2 - f**2) ** 2


LOSSES = {"qlike": qlike, "mse": mse}


def _nw_mean_test(d: pd.Series) -> tuple[float, float]:
    """Mean of d and its Newey-West t-stat (Bartlett, NW_LAGS lags)."""
    import statsmodels.api as sm

    fit = sm.OLS(d.to_numpy(), np.ones(len(d))).fit(
        cov_type="HAC", cov_kwds={"maxlags": NW_LAGS}
    )
    return float(fit.params[0]), float(fit.tvalues[0])


def dm_test(loss_model: pd.Series, loss_bench: pd.Series) -> dict[str, float]:
    """One-sided DM test. H1: the model's expected loss is below the benchmark's."""
    from scipy.stats import norm

    mean_diff, stat = _nw_mean_test(loss_model - loss_bench)
    return {"mean_diff": mean_diff, "dm_stat": stat, "p_one_sided": float(norm.cdf(stat))}


def mincer_zarnowitz(rv: pd.Series, f: pd.Series) -> dict[str, float]:
    """RV² = a + b·F² + e on annualised variance, Newey-West SE; Wald a=0, b=1."""
    import statsmodels.api as sm

    fit = sm.OLS((rv**2).to_numpy(), sm.add_constant((f**2).to_numpy())).fit(
        cov_type="HAC", cov_kwds={"maxlags": NW_LAGS}
    )
    wald = fit.wald_test((np.eye(2), np.array([0.0, 1.0])), use_f=False, scalar=True)
    return {
        "a": float(fit.params[0]),
        "a_se": float(fit.bse[0]),
        "b": float(fit.params[1]),
        "b_se": float(fit.bse[1]),
        "wald_p_a0_b1": float(wald.pvalue),
        "r2": float(fit.rsquared),
    }


def _period(fc: pd.DataFrame, name: str) -> pd.DataFrame:
    start, end = PERIODS[name]
    return fc.loc[start:end]


def evaluate() -> None:
    fc = pd.read_csv(FORECASTS_CSV, index_col="date", parse_dates=True)
    loss_rows, dm_rows, mz_rows = [], [], []
    for name in PERIODS:
        p = _period(fc, name)
        span = {"period": name, "n": len(p), "first_origin": p.index[0].date(),
                "last_origin": p.index[-1].date()}
        losses = {(ln, m): fn(p["rv"], p[m]) for ln, fn in LOSSES.items() for m in MODELS}
        for m in MODELS:
            row = dict(span, model=m)
            for ln in LOSSES:
                mean = losses[ln, m].mean()
                row[f"{ln}_mean"] = mean
                row[f"{ln}_pct_vs_naive"] = 100 * (mean / losses[ln, "naive"].mean() - 1)
            loss_rows.append(row)
            mz_rows.append(dict(span, model=m, **mincer_zarnowitz(p["rv"], p[m])))
        for ln in LOSSES:
            for model, bench in VS_NAIVE + VS_EWMA:
                res = dm_test(losses[ln, model], losses[ln, bench])
                p_bonf = min(1.0, N_VS_NAIVE * res["p_one_sided"]) if bench == "naive" else np.nan
                dm_rows.append(dict(span, loss=ln, model=model, benchmark=bench, **res,
                                    p_bonferroni=p_bonf))
    pd.DataFrame(loss_rows).to_csv(LOSSES_CSV, index=False, float_format="%.6g")
    pd.DataFrame(dm_rows).to_csv(DM_CSV, index=False, float_format="%.6g")
    pd.DataFrame(mz_rows).to_csv(MZ_CSV, index=False, float_format="%.6g")


# --- 4. report --------------------------------------------------------------


def _footnote(manifest: dict, period: str) -> str:
    return (f"Source: {manifest['source']}, S&P 500 ({manifest['ticker']}) daily closes "
            f"{manifest['first_date']} to {manifest['last_date']}. {period}")


def make_figures() -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    FIGURES.mkdir(parents=True, exist_ok=True)
    manifest = json.loads(MANIFEST.read_text())
    losses = pd.read_csv(LOSSES_CSV)
    fc = pd.read_csv(FORECASTS_CSV, index_col="date", parse_dates=True)
    colours = {"naive": "#888888", "ewma": "#1b7837", "garch": "#2166ac", "har": "#b2182b"}

    # (1) QLIKE relative to naive, by period.
    rel = losses[losses.model != "naive"].pivot(index="period", columns="model",
                                                 values="qlike_pct_vs_naive")
    rel = rel.loc[list(PERIODS)]
    full = rel.loc[FULL]
    best = full.idxmin()
    subs = rel.drop(index=FULL)
    beats = int((subs[best] < 0).sum())
    fig, ax = plt.subplots(figsize=(9, 5))
    x = np.arange(len(rel))
    for i, m in enumerate(rel.columns):
        ax.bar(x + (i - 1) * 0.27, rel[m], 0.27, label=m.upper(), color=colours[m])
    ax.axhline(0, color="black", lw=0.8)
    ax.set_xticks(x, [f"{p}\n(n = {n})" for p, n in zip(
        rel.index, losses[losses.model == "naive"].set_index("period").loc[rel.index, "n"])])
    ax.set_ylabel("Mean QLIKE, % change versus naive (negative = better)")
    ax.set_xlabel("Forecast origin period")
    ax.set_title(f"{best.upper()} cuts QLIKE by {abs(full[best]):.1f}% versus naive over "
                 f"{FULL}, and beats naive in {beats} of {len(subs)} subperiods", fontsize=11)
    ax.legend(frameon=False)
    p0 = losses[(losses.period == FULL)].iloc[0]
    fig.text(0.01, 0.01, _footnote(manifest, f"Forecast origins {p0.first_origin} to "
             f"{p0.last_origin}; 21-trading-day target."), fontsize=7, color="#444444")
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(FIGURES / "qlike_vs_naive.png", dpi=150)
    plt.close(fig)

    # (2) Forecasts against realised volatility, 2020.
    y = fc.loc["2020"] * 100
    peak_day = y["rv"].idxmax()
    peaks = {m: y[m].idxmax() for m in MODELS}
    lags = [y.index.get_loc(peaks[m]) - y.index.get_loc(peak_day) for m in MODELS]
    at_peak = y.loc[peak_day, list(MODELS)]
    rv_then = y.loc[list(peaks.values()), "rv"]
    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(y.index, y["rv"], color="black", lw=2.2, label="Realised, t+1 to t+21")
    for m in MODELS:
        ax.plot(y.index, y[m], color=colours[m], lw=1.2, label=f"{m.upper()} forecast")
    ax.set_ylabel("Annualised volatility (%)")
    ax.set_xlabel("Forecast origin date t (realised volatility covers t+1 to t+21)")
    ax.set_title(
        f"Every model missed March 2020: on {peak_day.day} {peak_day:%b} the next 21 days realised "
        f"{y['rv'].max():.0f}%, forecasts said {at_peak.min():.0f}–{at_peak.max():.0f}%\n"
        f"Forecasts peaked {min(lags)}–{max(lags)} trading days later, when realised vol "
        f"had fallen to {rv_then.min():.0f}–{rv_then.max():.0f}%",
        fontsize=10.5,
    )
    ax.legend(frameon=False)
    fig.text(0.01, 0.01, _footnote(manifest, f"Forecast origins {y.index[0].date()} to "
             f"{y.index[-1].date()}."), fontsize=7, color="#444444")
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(FIGURES / "forecasts_2020.png", dpi=150)
    plt.close(fig)


def _p(p: float) -> str:
    return "n/a" if pd.isna(p) else ("< 0.0001" if p < 1e-4 else f"{p:.4f}")


def h1_verdict(dm: pd.DataFrame) -> str:
    rows = dm[(dm.period == FULL) & (dm.loss == "qlike") & (dm.benchmark == "naive")]
    hit = (rows.mean_diff < 0) & (rows.p_one_sided < ALPHA / N_VS_NAIVE)
    return "supported" if hit.any() else "not supported"


def h2_verdict(dm: pd.DataFrame) -> str:
    rows = dm[(dm.period == FULL) & (dm.loss == "qlike") & (dm.benchmark == "ewma")]
    if ((rows.mean_diff < 0) & (rows.p_one_sided < ALPHA)).all():
        return "supported"
    if (rows.mean_diff > 0).all():
        return "contradicted"
    return "inconclusive"


def write_results_md() -> None:
    manifest = json.loads(MANIFEST.read_text())
    losses = pd.read_csv(LOSSES_CSV)
    dm = pd.read_csv(DM_CSV)
    mz = pd.read_csv(MZ_CSV)
    full = losses[losses.period == FULL].set_index("model")
    n, o1, o2 = int(full.n.iloc[0]), full.first_origin.iloc[0], full.last_origin.iloc[0]

    def dm_table(rows: pd.DataFrame, bonferroni: bool) -> list[str]:
        head = "| Model | Benchmark | Mean QLIKE difference | DM statistic | One-sided p |"
        sep = "|---|---|---|---|---|"
        if bonferroni:
            head += " Bonferroni p |"
            sep += "---|"
        out = [head, sep]
        for _, r in rows.iterrows():
            line = (f"| {r.model.upper()} | {r.benchmark.upper()} | {r.mean_diff:+.4f} | "
                    f"{r.dm_stat:+.2f} | {_p(r.p_one_sided)} |")
            out.append(line + (f" {_p(r.p_bonferroni)} |" if bonferroni else ""))
        return out

    def loss_table(period: str) -> list[str]:
        out = ["| Model | Mean QLIKE | QLIKE vs naive | Mean MSE (variance) | MSE vs naive |",
               "|---|---|---|---|---|"]
        for _, r in losses[losses.period == period].iterrows():
            out.append(f"| {r.model.upper()} | {r.qlike_mean:.4f} | {r.qlike_pct_vs_naive:+.1f}% "
                       f"| {r.mse_mean:.3g} | {r.mse_pct_vs_naive:+.1f}% |")
        return out

    def mz_table(period: str) -> list[str]:
        out = ["| Model | a (SE) | b (SE) | Wald p, a = 0 and b = 1 | R² |", "|---|---|---|---|---|"]
        for _, r in mz[mz.period == period].iterrows():
            out.append(f"| {r.model.upper()} | {r.a:.4f} ({r.a_se:.4f}) | {r.b:.3f} ({r.b_se:.3f}) "
                       f"| {_p(r.wald_p_a0_b1)} | {r.r2:.3f} |")
        return out

    q = dm[dm.loss == "qlike"]
    h1, h2 = h1_verdict(dm), h2_verdict(dm)
    L = [
        "# Block 1 results: forecast accuracy",
        "",
        "_Generated by `research/block1_forecasts.py` from the tables in `results/`. "
        "Do not edit by hand._",
        "",
        f"- **Data:** {manifest['source']}, S&P 500 ({manifest['ticker']}) daily closes, "
        f"{manifest['first_date']} to {manifest['last_date']} ({manifest['rows']} rows), "
        f"downloaded {manifest['download_date']}.",
        f"- **Out-of-sample:** {n} forecast origins, {o1} to {o2}.",
        "- **Target:** realised volatility of daily log returns from t+1 to t+21, "
        "sqrt(252 × mean squared return).",
        f"- **Tests:** one-sided Diebold-Mariano, Newey-West standard errors with {NW_LAGS} lags, "
        "p-values from the normal approximation. Losses are on annualised variance.",
        "",
        "## How it was done",
        "",
        "1. **Data.** Daily S&P 500 closes from Yahoo, turned into daily log returns.",
        "2. **Forecasts.** On every trading day t from 2005, each model forecasts the next 21 days "
        "of volatility using only returns up to t. GARCH and HAR are re-estimated at the start of "
        "each month on data up to that day. A test checks that changing any data after t leaves the "
        "forecast at t unchanged.",
        "3. **Scoring.** Each forecast is compared with the volatility that actually followed. "
        "QLIKE is the primary loss: it punishes under-forecasting a spike more than over-forecasting "
        "a calm spell, and it is not dominated by a handful of extreme days. MSE is secondary.",
        "4. **Testing.** A Diebold-Mariano test asks whether one model's average loss is lower than "
        "another's by more than chance would explain. Consecutive 21-day targets overlap, so "
        "neighbouring errors are correlated; Newey-West standard errors correct for that.",
        "",
        "## H1. At least one model beats the naive forecast",
        "",
        "> H0: E[QLIKE(model) − QLIKE(naive)] = 0. H1: < 0. One-sided DM test for each of EWMA, "
        "GARCH and HAR. **Supported** if at least one model has lower QLIKE with "
        "Bonferroni-adjusted p < 0.0167. Otherwise **not supported**.",
        "",
        *dm_table(q[(q.period == FULL) & (q.benchmark == "naive")], bonferroni=True),
        "",
        f"**Verdict: {h1}.**",
        "",
        "## H2. At a 21-day horizon, mean-reverting models beat EWMA",
        "",
        "> One-sided DM tests of GARCH vs EWMA and HAR vs EWMA. **Supported** if both have lower "
        "QLIKE than EWMA with p < 0.05. **Contradicted** if EWMA has lower QLIKE than both. "
        "Otherwise **inconclusive**.",
        "",
        *dm_table(q[(q.period == FULL) & (q.benchmark == "ewma")], bonferroni=False),
        "",
        f"**Verdict: {h2}.**",
        "",
        f"## Losses, {FULL}",
        "",
        *loss_table(FULL),
        "",
        f"## Mincer-Zarnowitz regressions, {FULL}",
        "",
        "Realised variance regressed on forecast variance. An unbiased forecast has a = 0 and "
        "b = 1; b below 1 means the forecast moves too much. No hypothesis attached.",
        "",
        *mz_table(FULL),
        "",
        "## By subperiod",
        "",
        "Reported without a hypothesis. Subperiods are assigned by forecast origin date.",
    ]
    for period in list(PERIODS)[1:]:
        L += ["", f"### {period}", "", "**Losses**", "", *loss_table(period), "",
              "**Against naive** (Bonferroni over 3 comparisons)", "",
              *dm_table(q[(q.period == period) & (q.benchmark == "naive")], bonferroni=True), "",
              "**Against EWMA**", "",
              *dm_table(q[(q.period == period) & (q.benchmark == "ewma")], bonferroni=False), "",
              "**Mincer-Zarnowitz**", "", *mz_table(period)]
    L += [
        "",
        "## Figures",
        "",
        "![QLIKE versus naive](figures/qlike_vs_naive.png)",
        "",
        "![Forecasts against realised volatility, 2020](figures/forecasts_2020.png)",
        "",
        "## Files",
        "",
        "- `block1_forecasts.csv`: realised volatility and every model's out-of-sample forecast, "
        "annualised, indexed by origin date t (input to Block 2)",
        "- `block1_losses.csv`, `block1_dm.csv` (QLIKE and MSE), `block1_mz.csv`: the tables above",
        "- `data_manifest.json`: data source, download date, range, row count and checksum",
        "",
    ]
    old = RESULTS_MD.read_text() if RESULTS_MD.exists() else ""
    tail = old[old.find(BLOCK2_MARKER):] if BLOCK2_MARKER in old else ""
    RESULTS_MD.write_text("\n".join(L) + tail)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--download", action="store_true", help="re-download the raw data")
    ap.add_argument("--report-only", action="store_true",
                    help="rebuild figures and RESULTS.md from saved tables")
    args = ap.parse_args()
    if not args.report_only:
        if args.download or not DATA_FILE.exists():
            download_data()
        run_forecasts()
        evaluate()
    make_figures()
    write_results_md()


if __name__ == "__main__":
    main()
